#define SETBIT(WORD,POS) WORD=WORD|(1<<POS)
#define CLRBIT(WORD,POS) WORD=WORD&~(1<<POS)
#define TOGGLEBIT(WORD,POS) WORD=WORD^(1<<POS)
#define WRITENIBBLE(WORD,POS,DATA) WORD=WORD&(~(15<<POS))|(DATA<<POS)
#define WRITEBYTE(WORD,POS,DATA) WORD=WORD&(~(0xff<<POS))|(DATA<<POS)
#define WRITEHWORD(WORD,POS,DATA) WORD=WORD&(~(0xffff<<POS))|(DATA<<POS)

